[package]
name = "pg_cpu_load"
version = "0.1.0"
authors = ["Sebastiaan Mannem <sebastiaan.mannem@enterprisedb.com>"]
edition = "2018"

[dependencies]
postgres = { version = "0.15", features = ["with-chrono"] }
args = "2.2.0"
getopts = "0.2.18"
chrono = "0.4"
